services:
  - type: web
    name: smartaqi-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
