"""Initial schema migration

Revision ID: 0cb59c012e45
Revises: 
Create Date: 2026-07-27 13:02:22.591204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb59c012e45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('area_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_name')
    )
    op.create_index(op.f('ix_sensor_nodes_id'), 'sensor_nodes', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_bot_token', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('alert_threshold_aqi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('alert_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_tickets_id'), 'alert_tickets', ['id'], unique=False)
    op.create_table('sensor_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm10', sa.Float(), nullable=False),
    sa.Column('co', sa.Float(), nullable=False),
    sa.Column('aqi', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_telemetry_id'), 'sensor_telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_telemetry_timestamp'), 'sensor_telemetry', ['timestamp'], unique=False)
    op.create_table('telemetry_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=False),
    sa.Column('pm10', sa.Float(), nullable=False),
    sa.Column('co', sa.Float(), nullable=False),
    sa.Column('aqi', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_anomalies_id'), 'telemetry_anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_anomalies_timestamp'), 'telemetry_anomalies', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_anomalies_timestamp'), table_name='telemetry_anomalies')
    op.drop_index(op.f('ix_telemetry_anomalies_id'), table_name='telemetry_anomalies')
    op.drop_table('telemetry_anomalies')
    op.drop_index(op.f('ix_sensor_telemetry_timestamp'), table_name='sensor_telemetry')
    op.drop_index(op.f('ix_sensor_telemetry_id'), table_name='sensor_telemetry')
    op.drop_table('sensor_telemetry')
    op.drop_index(op.f('ix_alert_tickets_id'), table_name='alert_tickets')
    op.drop_table('alert_tickets')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sensor_nodes_id'), table_name='sensor_nodes')
    op.drop_table('sensor_nodes')
    # ### end Alembic commands ###
